project:
  type: website

website:
  title: "NileQuantum Insights"
  image: images/logo.png
  favicon: images/favicon.png
  twitter-card:
    site: ""
  open-graph: true
  site-url: https://nilequantuminsights.com/
  
  google-analytics: "ua-164226979-1"
  search:
    location: navbar
    type: textbox
  reader-mode: false
  
  navbar:
    pinned: true
    logo: images/logo.png
    logo-alt: "NileQuantum Insights Brand"
    title: false
    collapse-below: lg
    right:
      - case-studies/index.qmd
      - text: "Our Services"
        href: services.qmd
      - talks/index.qmd
      - tutorials/index.qmd
      - text: "About NQI"
        menu: 
        - text: "Who we are"
          href: about-NQI.qmd
        - text: "Our Team"
          href: meet-the-team.qmd
        - text: "Contact us"
          href: contact.qmd
  sidebar: 
    - title: "About us"
      contents:
        - about-NQI.qmd
        - meet-the-team.qmd
        - contact.qmd
        - ts-and-cs.qmd
    - title: "Tutorials"
      contents:
        - tutorials/index.qmd

  page-navigation: true

  back-to-top-navigation: false

  page-footer:
    background: "#396E10"
    left: |
      Copyright &copy; 2023 [NileQuantum Insights](https://nilequantuminsights.com/). All rights reserved.
    center:  
      - href: https://github.com/tongakuot
        icon: github
        aria-label: GitHub
      - href: https://facebook.com/nilequantuminsights
        icon: facebook
        aria-label: Facebook
      - href: https://www.linkedin.com/showcase/nilequantuminsights
        icon: linkedin
        aria-label: LinkedIn
      - href: feeds.html
        icon: rss
        aria-label: NQI rss
    right: |
      [Terms & Conditions](/ts-and-cs.qmd)

format:
  html:
    theme: [lux, nqi.scss]
    css: nqi.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 250px

execute: 
  freeze: auto
